# Generated by Django 4.2.1 on 2023-05-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('uptime', models.IntegerField()),
                ('memoryUtelization', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=False)),
                ('speed', models.IntegerField()),
                ('interfaceType', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('macAddress', models.CharField(max_length=200)),
                ('inputPacketCount', models.IntegerField()),
                ('outputPacketCount', models.IntegerField()),
                ('inputErrorCount', models.IntegerField()),
                ('outputErrorCount', models.IntegerField()),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapi.router')),
            ],
        ),
    ]
