# Generated by Django 4.2.1 on 2023-05-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('temperature', models.FloatField(default=None, null=True)),
                ('uptime', models.IntegerField(default=None, null=True)),
                ('memoryUtelization', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='inputErrorCount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='inputPacketCount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interfaceType',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='macAddress',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='outputErrorCount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='outputPacketCount',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='speed',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='memoryUtelization',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='temperature',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='uptime',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portNumber', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('speed', models.IntegerField(default=None, null=True)),
                ('inputPacketCount', models.IntegerField(default=None, null=True)),
                ('outputPacketCount', models.IntegerField(default=None, null=True)),
                ('inputErrorCount', models.IntegerField(default=None, null=True)),
                ('outputErrorCount', models.IntegerField(default=None, null=True)),
                ('vlanId', models.IntegerField(default=None, null=True)),
                ('trunkSetting', models.BooleanField(default=False)),
                ('duplexSetting', models.CharField(default=None, max_length=200, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapi.switch')),
            ],
        ),
        migrations.CreateModel(
            name='MACTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddress', models.CharField(default=None, max_length=200)),
                ('vlan', models.IntegerField(default=None, null=True)),
                ('typeOf', models.CharField(default=None, max_length=200, null=True)),
                ('age', models.IntegerField(default=None, null=True)),
                ('securityViolation', models.BooleanField(default=False)),
                ('secureMac', models.BooleanField(default=False)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapi.port')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networkapi.switch')),
            ],
        ),
    ]
