# Generated by Django 4.2.1 on 2023-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0002_switch_alter_interface_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='community_string',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
