# Generated by Django 4.2.1 on 2023-05-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0004_alter_router_community_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='memoryUtelization',
            field=models.FloatField(default=None, null=True),
        ),
    ]
