# Generated by Django 4.2.1 on 2023-05-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0005_alter_router_memoryutelization'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='cpu_utelization',
            field=models.FloatField(default=None, null=True),
        ),
    ]
