# Generated by Django 4.2.1 on 2023-05-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0006_router_cpu_utelization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='cpu_utelization',
        ),
    ]
