# Generated by Django 4.2.1 on 2023-05-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0007_remove_router_cpu_utelization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='portNumber',
            field=models.CharField(max_length=100),
        ),
    ]
