# Generated by Django 4.2.1 on 2023-05-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0008_alter_port_portnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='memoryUtelization',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='temperature',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='uptime',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
