# Generated by Django 4.2.1 on 2023-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0009_alter_router_memoryutelization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='inputErrorCount',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='inputPacketCount',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ip',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='outputErrorCount',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='outputPacketCount',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='speed',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='state',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
