# Generated by Django 4.2.1 on 2023-05-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapi', '0010_alter_interface_inputerrorcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='interfaces',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='state',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
